In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as mpl
import math 
import seaborn as sea
import statistics
from scipy import stats
from numpy import percentile
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report 
from sklearn.metrics import accuracy_score 

In [2]:
path = "BankChurnersFNum.csv"
df = pd.read_csv(path)

del df["Unnamed: 0"]
del df["CLIENTNUM"]
del df["Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2"]
del df["Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1"]

df.head()


Attrition_Flag  Customer_Age  Gender  Dependent_count  Education_Level  \
0             1.0      0.409091     1.0              0.4              0.2   
1             1.0      0.363636     1.0              1.0              0.0   
2             1.0      0.704545     0.0              0.4              0.2   
3             1.0      0.431818     0.0              0.4              0.2   
4             1.0      0.477273     1.0              0.2              1.0   

   Marital_Status  Income_Category  Card_Category  Months_on_book  \
0             0.5             0.25            0.0        0.534884   
1             0.0             1.00            0.0        0.418605   
2             0.5             0.00            0.0        0.813953   
3             0.5             1.00            0.0        0.558140   
4             1.0             0.50            0.0        0.674419   

   Total_Relationship_Count  Months_Inactive_12_mon  Contacts_Count_12_mon  \
0                       0.4                0.166667               0.333333   
1                       0.8                0.500000               0.333333   
2                       0.8                0.333333               0.333333   
3                       1.0                0.166667               0.333333   
4                       0.8                0.333333               0.000000   

   Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  \
0      0.077747             0.495431         0.079970              0.972136   
1      0.160522             0.582837         0.152928              0.550310   
2      0.030162             0.270163         0.050792              0.828173   
3      0.393972             0.459674         0.385652              0.654799   
4      0.590751             0.715137         0.555617              0.608359   

   Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
0         0.040813        0.118644             0.604136               0.311311  
1         0.048793        0.271186             0.481536               0.217217  
2         0.074848        0.161017             0.430576               0.279279  
3         0.049216        0.093220             0.650665               0.080080  
4         0.047168        0.144068             0.665436               0.086086

implement Model Evaluation

In [3]:
X = df.drop(["Attrition_Flag"], axis=1)
Y = df["Attrition_Flag"]

In [4]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)
"""X_train = np.array(X[0:int(0.80*len(X))])
Y_train = np.array(Y[0:int(0.80*len(Y))])
X_test = np.array(X[int(0.80*len(X)):])
Y_test = np.array(Y[int(0.80*len(Y)):])"""

'X_train = np.array(X[0:int(0.80*len(X))])\nY_train = np.array(Y[0:int(0.80*len(Y))])\nX_test = np.array(X[int(0.80*len(X)):])\nY_test = np.array(Y[int(0.80*len(Y)):])'

In [5]:
LR = LogisticRegression()
KNN = KNeighborsClassifier()
NB = GaussianNB()
LSVM = LinearSVC()
NLSVM = SVC(kernel='rbf')
DT = DecisionTreeClassifier()
RF = RandomForestClassifier()
#
LR_fit = LR.fit(X_train, Y_train)
KNN_fit = KNN.fit(X_train, Y_train)
NB_fit = NB.fit(X_train, Y_train)
LSVM_fit = LSVM.fit(X_train, Y_train)
NLSVM_fit = NLSVM.fit(X_train, Y_train)
DT_fit = DT.fit(X_train, Y_train)
RF_fit = RF.fit(X_train, Y_train)
#
LR_pred = LR_fit.predict(X_test)
KNN_pred = KNN_fit.predict(X_test)
NB_pred = NB_fit.predict(X_test)
LSVM_pred = LSVM_fit.predict(X_test)
NLSVM_pred = NLSVM_fit.predict(X_test)
DT_pred = DT_fit.predict(X_test)
RF_pred = RF_fit.predict(X_test)
#
print("Logistic Regression is %f percent accurate" % (accuracy_score(LR_pred, Y_test)*100))
print(confusion_matrix(Y_test, LR_pred))  
print ('Report : ') 
print (classification_report(Y_test, LR_pred))
#print ('Accuracy Score :',accuracy_score(Y_test, LR_pred))
#
print("KNN is %f percent accurate" % (accuracy_score(KNN_pred, Y_test)*100))
print(confusion_matrix(Y_test, KNN_pred))  
print ('Report : ') 
print (classification_report(Y_test, KNN_pred))
#
print("Naive Bayes is %f percent accurate" % (accuracy_score(NB_pred, Y_test)*100))
print(confusion_matrix(Y_test, NB_pred))  
print ('Report : ') 
print (classification_report(Y_test, NB_pred))
#
print("Linear SVMs is %f percent accurate" % (accuracy_score(LSVM_pred, Y_test)*100))
print(confusion_matrix(Y_test, LSVM_pred))  
print ('Report : ') 
print (classification_report(Y_test, LSVM_pred))
#
print("Non Linear SVMs is %f percent accurate" % (accuracy_score(NLSVM_pred, Y_test)*100))
print(confusion_matrix(Y_test, NLSVM_pred))  
print ('Report : ') 
print (classification_report(Y_test, NLSVM_pred))
#
print("Decision Trees is %f percent accurate" % (accuracy_score(DT_pred, Y_test)*100))
print(confusion_matrix(Y_test, DT_pred))  
print ('Report : ') 
print (classification_report(Y_test, DT_pred))
#
print("Random Forests is %f percent accurate" % (accuracy_score(RF_pred, Y_test)*100))
print(confusion_matrix(Y_test, RF_pred))  
print ('Report : ') 
print (classification_report(Y_test, RF_pred))

Logistic Regression is 90.669478 percent accurate
[[ 188  129]
 [  48 1532]]
Report : 
              precision    recall  f1-score   support

         0.0       0.80      0.59      0.68       317
         1.0       0.92      0.97      0.95      1580

    accuracy                           0.91      1897
   macro avg       0.86      0.78      0.81      1897
weighted avg       0.90      0.91      0.90      1897

KNN is 89.298893 percent accurate
[[ 160  157]
 [  46 1534]]
Report : 
              precision    recall  f1-score   support

         0.0       0.78      0.50      0.61       317
         1.0       0.91      0.97      0.94      1580

    accuracy                           0.89      1897
   macro avg       0.84      0.74      0.77      1897
weighted avg       0.89      0.89      0.88      1897

Naive Bayes is 88.771745 percent accurate
[[ 209  108]
 [ 105 1475]]
Report : 
              precision    recall  f1-score   support

         0.0       0.67      0.66      0.66       317


In [6]:
#implement cross-validation
kfold = KFold(9, shuffle=True, random_state=1)

classifier = RandomForestClassifier()
scores = []

for i in range(9):
    result = next(kfold.split(df), None)
    
    X_train = df.iloc[result[0], 1:19]
    X_test = df.iloc[result[1], 1:19]
    
    y_train = df.iloc[result[0], 0]
    y_test = df.iloc[result[1], 0]
    
    classifier = classifier.fit(X_train,y_train)
    predicted = classifier.predict(X_test)
    scores.append(accuracy_score(y_test, predicted))
    
    print ('Confusion Matrix :') 
    print(confusion_matrix(y_test, predicted)) 
    print ('Accuracy Score :',accuracy_score(y_test, predicted)) 
    print ('Report : ') 
    print (classification_report(y_test, predicted)) 
    

print('Average K-Fold Score :' , np.mean(scores))

Confusion Matrix :
[[151  29]
 [ 14 860]]
Accuracy Score : 0.959203036053131
Report : 
              precision    recall  f1-score   support

         0.0       0.92      0.84      0.88       180
         1.0       0.97      0.98      0.98       874

    accuracy                           0.96      1054
   macro avg       0.94      0.91      0.93      1054
weighted avg       0.96      0.96      0.96      1054

Confusion Matrix :
[[151  29]
 [ 17 857]]
Accuracy Score : 0.9563567362428842
Report : 
              precision    recall  f1-score   support

         0.0       0.90      0.84      0.87       180
         1.0       0.97      0.98      0.97       874

    accuracy                           0.96      1054
   macro avg       0.93      0.91      0.92      1054
weighted avg       0.96      0.96      0.96      1054

Confusion Matrix :
[[149  31]
 [ 15 859]]
Accuracy Score : 0.9563567362428842
Report : 
              precision    recall  f1-score   support

         0.0       0.91     