In [1]:
from pandas import read_csv
import numpy as np
import warnings
from sklearn.model_selection import train_test_split,KFold
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn import datasets
from scipy.stats import uniform, truncnorm, randint
df = read_csv('BankChurners_2.csv')



In [2]:
X = df.iloc[:, 1:19].values 
Y = df.iloc[:, 0].values 
X_train, X_test, Y_train, Y_test = train_test_split( X , Y, test_size = 0.3)

In [3]:
#knn
fit_knn = KNeighborsClassifier().fit(X_train, Y_train)
pred_knn = fit_knn.predict(X_test)
print("K-Nearest Neighbor")
print("Percent accurate - {0}".format(accuracy_score(pred_knn, Y_test)*100))
print('Confusion Matrix  \n {0}'.format(confusion_matrix(pred_knn, Y_test)))
print('Report \n{0}'.format(classification_report(pred_knn, Y_test)))

K-Nearest Neighbor
Percent accurate - 83.94237526352775
Confusion Matrix  
 [[ 105   51]
 [ 406 2284]]
Report 
              precision    recall  f1-score   support

           0       0.21      0.67      0.31       156
           1       0.98      0.85      0.91      2690

    accuracy                           0.84      2846
   macro avg       0.59      0.76      0.61      2846
weighted avg       0.94      0.84      0.88      2846



In [4]:
print("Naive Bayes")
fit_ = GaussianNB().fit(X_train, Y_train)
pred_ = fit_.predict(X_test)
print("Percent accurate - {0}".format(accuracy_score(pred_, Y_test)*100))
print('Confusion Matrix \n {0}'.format(confusion_matrix(pred_, Y_test)))
print('Report\n{0}'.format(classification_report(pred_, Y_test)))

Naive Bayes
Percent accurate - 88.79128601546029
Confusion Matrix 
 [[ 338  146]
 [ 173 2189]]
Report
              precision    recall  f1-score   support

           0       0.66      0.70      0.68       484
           1       0.94      0.93      0.93      2362

    accuracy                           0.89      2846
   macro avg       0.80      0.81      0.81      2846
weighted avg       0.89      0.89      0.89      2846



In [5]:


print("Decision Trees")
fit_ = DecisionTreeClassifier().fit(X_train, Y_train)
pred = fit_.predict(X_test)
print("Percent accurate - {0}".format(accuracy_score(pred, Y_test)*100))
print('Confusion Matrix : \n {0}'.format(confusion_matrix(pred, Y_test)))
print('Report :\n{0}'.format(classification_report(pred, Y_test)))

Decision Trees
Percent accurate - 94.30780042164442
Confusion Matrix : 
 [[ 423   74]
 [  88 2261]]
Report :
              precision    recall  f1-score   support

           0       0.83      0.85      0.84       497
           1       0.97      0.96      0.97      2349

    accuracy                           0.94      2846
   macro avg       0.90      0.91      0.90      2846
weighted avg       0.94      0.94      0.94      2846



In [7]:
print("Linear SVMs")
fit_ = LinearSVC().fit(X_train, Y_train)
pred = fit_.predict(X_test)
print("Percent accurate - {0}".format(accuracy_score(pred, Y_test)*100))
print('Confusion Matrix : \n {0}'.format(confusion_matrix(pred, Y_test)))
print('Report :\n{0}'.format(classification_report(pred, Y_test)))

Linear SVMs
Percent accurate - 90.30217849613493
Confusion Matrix : 
 [[ 307   72]
 [ 204 2263]]
Report :
              precision    recall  f1-score   support

           0       0.60      0.81      0.69       379
           1       0.97      0.92      0.94      2467

    accuracy                           0.90      2846
   macro avg       0.78      0.86      0.82      2846
weighted avg       0.92      0.90      0.91      2846



c:\users\liubomyr\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


In [10]:



print("Random Forest")
fit_ = RandomForestClassifier().fit(X_train, Y_train)
pred = fit_.predict(X_test)
print("Percent accurate - {0}".format(accuracy_score(pred, Y_test)*100))
print('Confusion Matrix : \n {0}'.format(confusion_matrix(pred, Y_test)))
print('Report :\n{0}'.format(classification_report(pred, Y_test)))

Random Forest
Percent accurate - 96.83766690091356
Confusion Matrix : 
 [[ 441   20]
 [  70 2315]]
Report :
              precision    recall  f1-score   support

           0       0.86      0.96      0.91       461
           1       0.99      0.97      0.98      2385

    accuracy                           0.97      2846
   macro avg       0.93      0.96      0.94      2846
weighted avg       0.97      0.97      0.97      2846



In [11]:

print("Non Linear SVMs")
a = SVC(kernel='rbf')
fit_ = a.fit(X_train, Y_train)
pred = fit_.predict(X_test)
print("Percent accurate - {0}" .format(accuracy_score(pred, Y_test)*100))
print('Confusion Matrix : \n {0}'.format(confusion_matrix(pred, Y_test)))
print('Report :\n{0}'.format(classification_report(pred, Y_test)))

Non Linear SVMs
Percent accurate - 88.12368236120871
Confusion Matrix : 
 [[ 187   14]
 [ 324 2321]]
Report :
              precision    recall  f1-score   support

           0       0.37      0.93      0.53       201
           1       0.99      0.88      0.93      2645

    accuracy                           0.88      2846
   macro avg       0.68      0.90      0.73      2846
weighted avg       0.95      0.88      0.90      2846

