In [1]:
from pandas import read_csv
import numpy as np
import warnings
from sklearn.model_selection import train_test_split,KFold
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn import datasets
from scipy.stats import uniform, truncnorm, randint
bank = read_csv('BankChurnML.csv')

bank

Attrition_Flag  Customer_Age  Gender  Dependent_count  Education_Level  \
0                  1      0.409091       1                2                2   
1                  1      0.363636       1                5                5   
2                  1      0.704545       0                2                2   
3                  1      0.431818       0                2                2   
4                  1      0.477273       1                1                1   
...              ...           ...     ...              ...              ...   
9480               1      0.681818       0                1                2   
9481               0      0.340909       1                2                3   
9482               0      0.409091       0                1                3   
9483               0      0.090909       1                2                2   
9484               0      0.386364       0                2                2   

      Marital_Status  Income_Category  Card_Category  Months_on_book  \
0                  1                1              0        0.534884   
1                  1                0              0        0.418605   
2                  1                4              0        0.813953   
3                  1                2              0        0.558140   
4                  0                2              0        0.674419   
...              ...              ...            ...             ...   
9480               2                4              0        0.860465   
9481               0                1              0        0.279070   
9482               1                4              0        0.534884   
9483               1                1              0        0.534884   
9484               1                4              3        0.279070   

      Total_Relationship_Count  ...  Credit_Limit  Total_Revolving_Bal  \
0                            3  ...      0.077747             0.495431   
1                            5  ...      0.160522             0.582837   
2                            5  ...      0.030162             0.270163   
3                            6  ...      0.393972             0.459674   
4                            5  ...      0.590751             0.715137   
...                        ...  ...           ...                  ...   
9480                         4  ...      0.068013             0.240763   
9481                         4  ...      0.085819             0.868494   
9482                         5  ...      0.120042             0.000000   
9483                         4  ...      0.116172             0.000000   
9484                         6  ...      0.270566             0.779102   

      Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
0            0.079970              0.972136         0.040813        0.118644   
1            0.152928              0.550310         0.048793        0.271186   
2            0.050792              0.828173         0.074848        0.161017   
3            0.385652              0.654799         0.049216        0.093220   
4            0.555617              0.608359         0.047168        0.144068   
...               ...                   ...              ...             ...   
9480         0.089213              0.348297         0.994634        0.932203   
9481         0.060499              0.529412         0.582827        0.500000   
9482         0.156637              0.541022         0.690651        0.423729   
9483         0.152928              0.321207         0.556772        0.440678   
9484         0.244082              0.451238         0.690863        0.432203   

      Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  \
0                0.604136               0.311311   
1                0.481536               0.217217   
2                0.430576               0.279279   
3                0.650665               0.080080   
4                0.665436               0.086086   
...               

# Split data to train and test sets

In [2]:
X = bank.iloc[:, 1:19].values 
Y = bank.iloc[:, 0].values 
X_train, X_test, Y_train, Y_test = train_test_split( X , Y, test_size = 0.3)

# Methods which I applied

In [3]:
warnings.simplefilter('ignore')
LR = LogisticRegression()
KNN = KNeighborsClassifier()
NB = GaussianNB()
LSVM = LinearSVC()
NLSVM = SVC(kernel='rbf')
DT = DecisionTreeClassifier()
RF = RandomForestClassifier()
#
LR_fit = LR.fit(X_train, Y_train)
KNN_fit = KNN.fit(X_train, Y_train)
NB_fit = NB.fit(X_train, Y_train)
LSVM_fit = LSVM.fit(X_train, Y_train)
NLSVM_fit = NLSVM.fit(X_train, Y_train)
DT_fit = DT.fit(X_train, Y_train)
RF_fit = RF.fit(X_train, Y_train)
#
LR_pred = LR_fit.predict(X_test)
KNN_pred = KNN_fit.predict(X_test)
NB_pred = NB_fit.predict(X_test)
LSVM_pred = LSVM_fit.predict(X_test)
NLSVM_pred = NLSVM_fit.predict(X_test)
DT_pred = DT_fit.predict(X_test)
RF_pred = RF_fit.predict(X_test)
#===========================================================
print("Logistic Regression is {0} percent accurate".format(accuracy_score(LR_pred, Y_test)*100))
print('Confusion Matrix : \n {0}'.format(confusion_matrix(LR_pred, Y_test)))
print('Report :\n{0}'.format(classification_report(LR_pred, Y_test)))
#===========================================================
print("KNN is {0} percent accurate".format(accuracy_score(KNN_pred, Y_test)*100))
print('Confusion Matrix : \n {0}'.format(confusion_matrix(KNN_pred, Y_test)))
print('Report :\n{0}'.format(classification_report(KNN_pred, Y_test)))
#===========================================================
print("Naive Bayes is {0} percent accurate".format(accuracy_score(NB_pred, Y_test)*100))
print('Confusion Matrix : \n {0}'.format(confusion_matrix(NB_pred, Y_test)))
print('Report :\n{0}'.format(classification_report(NB_pred, Y_test)))
#===========================================================
print("Linear SVMs is {0} percent accurate".format(accuracy_score(LSVM_pred, Y_test)*100))
print('Confusion Matrix : \n {0}'.format(confusion_matrix(LSVM_pred, Y_test)))
print('Report :\n{0}'.format(classification_report(LSVM_pred, Y_test)))
#===========================================================
print("Non Linear SVMs is {0} percent accurate" .format(accuracy_score(NLSVM_pred, Y_test)*100))
print('Confusion Matrix : \n {0}'.format(confusion_matrix(NLSVM_pred, Y_test)))
print('Report :\n{0}'.format(classification_report(NLSVM_pred, Y_test)))
#===========================================================
print("Decision Trees is {0} percent accurate".format(accuracy_score(DT_pred, Y_test)*100))
print('Confusion Matrix : \n {0}'.format(confusion_matrix(DT_pred, Y_test)))
print('Report :\n{0}'.format(classification_report(DT_pred, Y_test)))
#===========================================================
print("Random Forests is {0} percent accurate".format(accuracy_score(RF_pred, Y_test)*100))
print('Confusion Matrix : \n {0}'.format(confusion_matrix(RF_pred, Y_test)))
print('Report :\n{0}'.format(classification_report(RF_pred, Y_test)))


Logistic Regression is 90.09135628952917 percent accurate
Confusion Matrix : 
 [[ 264   65]
 [ 217 2300]]
Report :
              precision    recall  f1-score   support

           0       0.55      0.80      0.65       329
           1       0.97      0.91      0.94      2517

    accuracy                           0.90      2846
   macro avg       0.76      0.86      0.80      2846
weighted avg       0.92      0.90      0.91      2846

KNN is 84.8208011243851 percent accurate
Confusion Matrix : 
 [[  97   48]
 [ 384 2317]]
Report :
              precision    recall  f1-score   support

           0       0.20      0.67      0.31       145
           1       0.98      0.86      0.91      2701

    accuracy                           0.85      2846
   macro avg       0.59      0.76      0.61      2846
weighted avg       0.94      0.85      0.88      2846

Naive Bayes is 88.51018973998595 percent accurate
Confusion Matrix : 
 [[ 302  148]
 [ 179 2217]]
Report :
              precision   

# Tuning Parametrs and Cross-Validation 

In [19]:
random_forest = RandomForestClassifier()

params = {'n_estimators': [*range(100, 1100, 100)], 'max_features': [*range(1, 20)]}

rscv = RandomizedSearchCV(estimator=random_forest, param_distributions=params, random_state=0)
rscv.fit(X_train, Y_train)
values = rscv.best_params_
random_forest_best = RandomForestClassifier(n_estimators = values['n_estimators'], max_features = values['max_features'])
random_forest_best.fit(X_train, Y_train)
Y_pred = random_forest_best.predict(X_test)
print("Random Forests before tuning : {0} percent accurate".format(accuracy_score(RF_pred, Y_test)*100))
print("Random Forests after tuning : {0} percent accurate".format(accuracy_score(Y_test, Y_pred)*100))

Random Forests before tuning : 96.38088545326774 percent accurate
Random Forests after tuning : 96.5917076598735 percent accurate


In [ ]:
kfold = KFold(7, shuffle=True, random_state=1)
k_fold = []
classifier = RandomForestClassifier()

for i in range(7):
    result  = next(kfold.split(bank), None)
    X_train = bank.iloc[result[0], 1:19]
    X_test  = bank.iloc[result[1], 1:19]
    Y_train = bank.iloc[result[0], 0]
    Y_test  = bank.iloc[result[1], 0]
    
    classifier = classifier.fit(X_train,Y_train)
    predicted = classifier.predict(X_test)
    k_fold.append(accuracy_score(Y_test, predicted))

print('Average K-Fold Score :' , np.mean(k_fold))