In [1]:
from pandas import read_csv
import numpy as np
import warnings
from sklearn.model_selection import train_test_split,KFold
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

bank = read_csv('BankChurnML.csv')

bank

Attrition_Flag  Customer_Age  Gender  Dependent_count  Education_Level  \
0                  1      0.382979       1                2                2   
1                  1      0.340426       1                5                5   
2                  1      0.659574       0                2                2   
3                  1      0.404255       0                2                2   
4                  1      0.446809       1                1                1   
...              ...           ...     ...              ...              ...   
9480               1      0.638298       0                1                2   
9481               0      0.319149       1                2                2   
9482               0      0.382979       0                1                3   
9483               0      0.085106       1                2                2   
9484               0      0.361702       0                2                2   

      Marital_Status  Income_Category  Card_Category  Months_on_book  \
0                  1                1              0        0.534884   
1                  1                0              0        0.418605   
2                  1                4              0        0.813953   
3                  1                0              0        0.558140   
4                  0                2              0        0.674419   
...              ...              ...            ...             ...   
9480               2                4              0        0.860465   
9481               0                1              0        0.279070   
9482               1                4              0        0.534884   
9483               2                1              0        0.534884   
9484               1                4              3        0.279070   

      Total_Relationship_Count  ...  Credit_Limit  Total_Revolving_Bal  \
0                            3  ...      0.077747             0.495431   
1                            5  ...      0.160522             0.582837   
2                            5  ...      0.030162             0.270163   
3                            6  ...      0.393972             0.459674   
4                            5  ...      0.590751             0.715137   
...                        ...  ...           ...                  ...   
9480                         4  ...      0.068013             0.240763   
9481                         4  ...      0.085819             0.868494   
9482                         5  ...      0.120042             0.000000   
9483                         4  ...      0.116172             0.000000   
9484                         6  ...      0.270566             0.779102   

      Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
0            0.079970              0.405063         0.032158        0.108527   
1            0.152928              0.244628         0.038444        0.248062   
2            0.050792              0.350309         0.058974        0.147287   
3            0.385652              0.284369         0.038778        0.085271   
4            0.555617              0.266706         0.037165        0.131783   
...               ...                   ...              ...             ...   
9480         0.089213              0.167795         0.783688        0.852713   
9481         0.060499              0.236679         0.459219        0.457364   
9482         0.156637              0.241095         0.544175        0.387597   
9483         0.152928              0.157492         0.438689        0.403101   
9484         0.244082              0.206947         0.544342        0.395349   

      Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  \
0                0.227787               0.311311   
1                0.183091               0.217217   
2                0.164513               0.279279   
3                0.244750               0.080080   
4                0.250135               0.086086   
...               

# Split data to train and test sets

In [2]:
X = bank.iloc[:, 1:19].values 
Y = bank.iloc[:, 0].values 
X_train, X_test, Y_train, Y_test = train_test_split( X , Y, test_size = 0.3)

# Methods which I applied

In [9]:
warnings.simplefilter('ignore')
LR = LogisticRegression()
KNN = KNeighborsClassifier()
NB = GaussianNB()
LSVM = LinearSVC()
NLSVM = SVC(kernel='rbf')
DT = DecisionTreeClassifier()
RF = RandomForestClassifier()
#
LR_fit = LR.fit(X_train, Y_train)
KNN_fit = KNN.fit(X_train, Y_train)
NB_fit = NB.fit(X_train, Y_train)
LSVM_fit = LSVM.fit(X_train, Y_train)
NLSVM_fit = NLSVM.fit(X_train, Y_train)
DT_fit = DT.fit(X_train, Y_train)
RF_fit = RF.fit(X_train, Y_train)
#
LR_pred = LR_fit.predict(X_test)
KNN_pred = KNN_fit.predict(X_test)
NB_pred = NB_fit.predict(X_test)
LSVM_pred = LSVM_fit.predict(X_test)
NLSVM_pred = NLSVM_fit.predict(X_test)
DT_pred = DT_fit.predict(X_test)
RF_pred = RF_fit.predict(X_test)
#===========================================================
print("Logistic Regression is {0} percent accurate".format(accuracy_score(LR_pred, Y_test)*100))
print('Confusion Matrix : \n {0}'.format(confusion_matrix(LR_pred, Y_test)))
print('Report :\n{0}'.format(classification_report(LR_pred, Y_test)))
#===========================================================
print("KNN is {0} percent accurate".format(accuracy_score(KNN_pred, Y_test)*100))
print('Confusion Matrix : \n {0}'.format(confusion_matrix(KNN_pred, Y_test)))
print('Report :\n{0}'.format(classification_report(KNN_pred, Y_test)))
#===========================================================
print("Naive Bayes is {0} percent accurate".format(accuracy_score(NB_pred, Y_test)*100))
print('Confusion Matrix : \n {0}'.format(confusion_matrix(NB_pred, Y_test)))
print('Report :\n{0}'.format(classification_report(NB_pred, Y_test)))
#===========================================================
print("Linear SVMs is {0} percent accurate".format(accuracy_score(LSVM_pred, Y_test)*100))
print('Confusion Matrix : \n {0}'.format(confusion_matrix(LSVM_pred, Y_test)))
print('Report :\n{0}'.format(classification_report(LSVM_pred, Y_test)))
#===========================================================
print("Non Linear SVMs is {0} percent accurate" .format(accuracy_score(NLSVM_pred, Y_test)*100))
print('Confusion Matrix : \n {0}'.format(confusion_matrix(NLSVM_pred, Y_test)))
print('Report :\n{0}'.format(classification_report(NLSVM_pred, Y_test)))
#===========================================================
print("Decision Trees is {0} percent accurate".format(accuracy_score(DT_pred, Y_test)*100))
print('Confusion Matrix : \n {0}'.format(confusion_matrix(DT_pred, Y_test)))
print('Report :\n{0}'.format(classification_report(DT_pred, Y_test)))
#===========================================================
print("Random Forests is {0} percent accurate".format(accuracy_score(RF_pred, Y_test)*100))
print('Confusion Matrix : \n {0}'.format(confusion_matrix(RF_pred, Y_test)))
print('Report :\n{0}'.format(classification_report(RF_pred, Y_test)))


Logistic Regression is 89.96309963099631 percent accurate
Confusion Matrix : 
 [[ 126   38]
 [  98 1093]]
Report :
              precision    recall  f1-score   support

           0       0.56      0.77      0.65       164
           1       0.97      0.92      0.94      1191

    accuracy                           0.90      1355
   macro avg       0.76      0.84      0.80      1355
weighted avg       0.92      0.90      0.91      1355

KNN is 85.83025830258303 percent accurate
Confusion Matrix : 
 [[  57   25]
 [ 167 1106]]
Report :
              precision    recall  f1-score   support

           0       0.25      0.70      0.37        82
           1       0.98      0.87      0.92      1273

    accuracy                           0.86      1355
   macro avg       0.62      0.78      0.65      1355
weighted avg       0.93      0.86      0.89      1355

Naive Bayes is 88.33948339483395 percent accurate
Confusion Matrix : 
 [[ 145   79]
 [  79 1052]]
Report :
              precision  

# Cross-Validation 

In [8]:
kfold = KFold(7, shuffle=True, random_state=1)
k_fold = []
classifier = RandomForestClassifier()

for i in range(7):
    result  = next(kfold.split(bank), None)
    X_train = bank.iloc[result[0], 1:19]
    X_test  = bank.iloc[result[1], 1:19]
    Y_train = bank.iloc[result[0], 0]
    Y_test  = bank.iloc[result[1], 0]
    
    classifier = classifier.fit(X_train,Y_train)
    predicted = classifier.predict(X_test)
    scores.append(accuracy_score(Y_test, predicted))

print('Average K-Fold Score :' , np.mean(scores))

Average K-Fold Score : 0.9597754048887737
