In [1]:
import pandas
import numpy as np
import seaborn as sns

from matplotlib import pyplot as plt

from sklearn.model_selection import train_test_split 
from sklearn.model_selection import KFold
from sklearn.ensemble import RandomForestClassifier  
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score


from sklearn.feature_selection import SelectKBest, f_classif, chi2,  SelectFromModel


In [2]:
churners = pandas.read_csv("BankChurnersUpdated.csv")
churners_original = pandas.read_csv("BankChurners.csv")

churners


Attrition_Flag  Customer_Age  Gender  Dependent_count  Education_Level  \
0                0.0      0.409091     1.0              0.4              0.4   
1                0.0      0.363636     1.0              1.0              1.0   
2                0.0      0.704545     0.0              0.4              0.4   
3                0.0      0.431818     0.0              0.4              0.4   
4                0.0      0.477273     1.0              0.2              0.2   
...              ...           ...     ...              ...              ...   
9197             1.0      0.659091     0.0              0.6              1.0   
9198             1.0      0.340909     1.0              0.4              0.6   
9199             1.0      0.409091     0.0              0.2              0.6   
9200             1.0      0.090909     1.0              0.4              0.4   
9201             1.0      0.386364     0.0              0.4              0.4   

      Marital_Status  Income_Category  Card_Category  Months_on_book  \
0                0.5         0.272727            0.0        0.534884   
1                0.5         1.000000            0.0        0.418605   
2                0.5         0.000000            0.0        0.813953   
3                0.5         0.272727            0.0        0.558140   
4                0.0         0.454545            0.0        0.674419   
...              ...              ...            ...             ...   
9197             1.0         0.454545            0.0        0.790698   
9198             0.0         0.272727            0.0        0.279070   
9199             0.5         0.000000            0.0        0.534884   
9200             0.5         0.272727            0.0        0.534884   
9201             0.5         0.000000            1.0        0.279070   

      Total_Relationship_Count  ...  Credit_Limit  Total_Revolving_Bal  \
0                          0.4  ...      0.077747             0.495431   
1                          0.8  ...      0.160522             0.582837   
2                          0.8  ...      0.030162             0.270163   
3                          1.0  ...      0.393972             0.459674   
4                          0.8  ...      0.590751             0.715137   
...                        ...  ...           ...                  ...   
9197                       0.6  ...      0.399626             1.000000   
9198                       0.6  ...      0.085819             0.868494   
9199                       0.8  ...      0.120042             0.000000   
9200                       0.6  ...      0.116172             0.000000   
9201                       1.0  ...      0.270566             0.779102   

      Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
0            0.079970              0.972136         0.041042        0.114754   
1            0.152928              0.550310         0.049066        0.262295   
2            0.050792              0.828173         0.075268        0.155738   
3            0.385652              0.654799         0.049492        0.090164   
4            0.555617              0.608359         0.047433        0.139344   
...               ...                   ...              ...             ...   
9197         0.351665              0.035604         0.390471        0.352459   
9198         0.060499              0.529412         0.586097        0.483607   
9199         0.156637              0.541022         0.694525        0.409836   
9200         0.152928              0.321207         0.559895        0.426230   
9201         0.244082              0.451238         0.694738        0.418033   

      Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  \
0                0.595355               0.311311   
1                0.478536               0.217217   
2                0.429979               0.279279   
3                0.639690               0.080080   
4                0.653765               0.086086   
...               

In [3]:
churners_X = churners.drop(["Attrition_Flag", 
                            "Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1", 
                            "Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2"], 
                            axis=1)
columns = pandas.DataFrame(churners_original.columns[2:21])

X = churners_X.values
y = churners["Attrition_Flag"].values

X_train, X_test, y_train, y_test = train_test_split( 
              X, y, test_size = 0.3)

churners_X

Customer_Age  Gender  Dependent_count  Education_Level  Marital_Status  \
0         0.409091     1.0              0.4              0.4             0.5   
1         0.363636     1.0              1.0              1.0             0.5   
2         0.704545     0.0              0.4              0.4             0.5   
3         0.431818     0.0              0.4              0.4             0.5   
4         0.477273     1.0              0.2              0.2             0.0   
...            ...     ...              ...              ...             ...   
9197      0.659091     0.0              0.6              1.0             1.0   
9198      0.340909     1.0              0.4              0.6             0.0   
9199      0.409091     0.0              0.2              0.6             0.5   
9200      0.090909     1.0              0.4              0.4             0.5   
9201      0.386364     0.0              0.4              0.4             0.5   

      Income_Category  Card_Category  Months_on_book  \
0            0.272727            0.0        0.534884   
1            1.000000            0.0        0.418605   
2            0.000000            0.0        0.813953   
3            0.272727            0.0        0.558140   
4            0.454545            0.0        0.674419   
...               ...            ...             ...   
9197         0.454545            0.0        0.790698   
9198         0.272727            0.0        0.279070   
9199         0.000000            0.0        0.534884   
9200         0.272727            0.0        0.534884   
9201         0.000000            1.0        0.279070   

      Total_Relationship_Count  Months_Inactive_12_mon  Contacts_Count_12_mon  \
0                          0.4                     0.2                    0.4   
1                          0.8                     0.6                    0.4   
2                          0.8                     0.4                    0.4   
3                          1.0                     0.2                    0.4   
4                          0.8                     0.4                    0.0   
...                        ...                     ...                    ...   
9197                       0.6                     0.6                    0.6   
9198                       0.6                     0.4                    0.6   
9199                       0.8                     0.6                    0.8   
9200                       0.6                     0.6                    0.6   
9201                       1.0                     0.4                    0.8   

      Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  \
0         0.077747             0.495431         0.079970   
1         0.160522             0.582837         0.152928   
2         0.030162             0.270163         0.050792   
3         0.393972             0.459674         0.385652   
4         0.590751             0.715137         0.555617   
...            ...                  ...              ...   
9197      0.399626             1.000000         0.351665   
9198      0.085819             0.868494         0.060499   
9199      0.120042             0.000000         0.156637   
9200      0.116172             0.000000         0.152928   
9201      0.270566             0.779102         0.244082   

      Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
0                 0.972136         0.041042        0.114754   
1                 0.550310         0.049066        0.262295   
2                 0.828173         0.075268        0.155738   
3                 0.654799         0.049492        0.090164   
4                 0.608359         0.047433        0.139344   
...                    ...              ...             ...   
9197              0.035604         0.390471        0.352459   
9198              0.529412         0.586097        0.483607   
9199              0.541022         0.694525        0.409836   
9200              0.321207         0.559895     

In [4]:
classifier =  RandomForestClassifier()
classifier = classifier.fit(X_train, y_train)
predicted = classifier.predict(X_test)

before_feature_selection = 'Confusion Matrix : \n' + str(confusion_matrix(y_test, predicted)) + '\n Accuracy Score : ' + \
                str(accuracy_score(y_test, predicted)) + '\n f1_score: ' + str(f1_score(y_test, predicted)) + \
               "\n recall_score: " + str(recall_score(y_test,predicted)) + "\n precision_score: " + str(precision_score(y_test,predicted)) + "\n"


In [5]:
best_features_selector = SelectKBest(chi2)
fit = best_features_selector.fit(X, y)
scores = pandas.DataFrame(fit.scores_)

features_scores = pandas.concat([columns, scores], axis=1)
features_scores.columns = ('Features', 'Score')
best_features = []

for feature in features_scores.values:
    if feature[1] > 2:
        best_features.append(feature[0])

print("Best features are: ", best_features)
features_scores

Best features are:  ['Gender', 'Total_Relationship_Count', 'Months_Inactive_12_mon', 'Contacts_Count_12_mon', 'Total_Revolving_Bal', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt', 'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio']


Features       Score
0               Customer_Age    0.107268
1                     Gender    4.306045
2            Dependent_count    0.518111
3            Education_Level    0.004307
4             Marital_Status    0.223864
5            Income_Category    0.161561
6              Card_Category    0.032142
7             Months_on_book    0.010902
8   Total_Relationship_Count   41.121564
9     Months_Inactive_12_mon   19.723829
10     Contacts_Count_12_mon   27.216401
11              Credit_Limit    1.494584
12       Total_Revolving_Bal  139.676611
13           Avg_Open_To_Buy    0.014429
14      Total_Amt_Chng_Q4_Q1    5.198456
15           Total_Trans_Amt   31.728143
16            Total_Trans_Ct   98.952628
17       Total_Ct_Chng_Q4_Q1   38.277096
18     Avg_Utilization_Ratio   84.581779

In [6]:
X_best = churners[best_features]
X_train, X_test, y_train, y_test = train_test_split(X_best, y, test_size=0.3)

print("Results before model upgrade: \n")
print(before_feature_selection)

print("Results after model upgrade: \n ")
classifier =  RandomForestClassifier()
classifier = classifier.fit(X_train, y_train)
predicted = classifier.predict(X_test)

print ('Confusion Matrix :') 
print(confusion_matrix(y_test, predicted)) 
print ('Accuracy Score :',accuracy_score(y_test, predicted)) 
print ('f1_score: ', f1_score(y_test, predicted)) 
print ("recall_score", recall_score(y_test,predicted))
print ("precision_score: ", precision_score(y_test,predicted))


Results before model upgrade: 

Confusion Matrix : 
[[2249   38]
 [  99  375]]
 Accuracy Score : 0.9503802969938429
 f1_score: 0.8455467869222096
 recall_score: 0.7911392405063291
 precision_score: 0.9079903147699758

Results after model upgrade: 
 
Confusion Matrix :
[[2264   40]
 [  74  383]]
Accuracy Score : 0.9587106120970663
f1_score:  0.8704545454545455
recall_score 0.838074398249453
precision_score:  0.9054373522458629


In [7]:
print(X.shape)

classifier = ExtraTreesClassifier(n_estimators=50)
classifier = classifier.fit(X, y)  

model = SelectFromModel(classifier, prefit=True)
X_new = model.transform(X)

print(X_new.shape)

print("Results before model upgrade: \n ")
print(before_feature_selection)

X_train, X_test, y_train, y_test = train_test_split( 
              X_new, y, test_size = 0.3)

classifier =  RandomForestClassifier()
classifier = classifier.fit(X_train, y_train)
predicted = classifier.predict(X_test)

print("Results after model upgrade: \n ")
print ('Confusion Matrix :') 
print(confusion_matrix(y_test, predicted)) 
print ('Accuracy Score :',accuracy_score(y_test, predicted)) 
print ('f1_score: ', f1_score(y_test, predicted)) 
print ("recall_score", recall_score(y_test,predicted))
print ("precision_score: ", precision_score(y_test,predicted))

(9202, 19)
(9202, 5)
Results before model upgrade: 
 
Confusion Matrix : 
[[2249   38]
 [  99  375]]
 Accuracy Score : 0.9503802969938429
 f1_score: 0.8455467869222096
 recall_score: 0.7911392405063291
 precision_score: 0.9079903147699758

Results after model upgrade: 
 
Confusion Matrix :
[[2289   56]
 [  76  340]]
Accuracy Score : 0.952191235059761
f1_score:  0.8374384236453203
recall_score 0.8173076923076923
precision_score:  0.8585858585858586
