In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as mpl
import math 
import seaborn as sea
import statistics
from scipy import stats
from numpy import percentile
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report 
from sklearn.metrics import accuracy_score
from sklearn.model_selection import RandomizedSearchCV


from sklearn.datasets import make_regression
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression

In [2]:

#dataset = pd.get_dummies(dataset)


df = pd.read_csv("BankChurnML.csv")
del df["Unnamed: 0"]
del df["CLIENTNUM"]
del df["Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2"]
del df["Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1"]


In [3]:
#train and test sets
X = df.drop(["Attrition_Flag"], axis=1)
Y = np.array(df['Attrition_Flag']) 
X_train, X_test, Y_train, Y_test = train_test_split( X , Y, test_size = 0.3)

In [4]:
# Methods of Model Evaluation
LR = LogisticRegression()
KNN = KNeighborsClassifier()
NB = GaussianNB()
LSVM = LinearSVC()
NLSVM = SVC(kernel='rbf')
DT = DecisionTreeClassifier()
RF = RandomForestClassifier()
#
LR_fit = LR.fit(X_train, Y_train)
KNN_fit = KNN.fit(X_train, Y_train)
NB_fit = NB.fit(X_train, Y_train)
LSVM_fit = LSVM.fit(X_train, Y_train)
NLSVM_fit = NLSVM.fit(X_train, Y_train)
DT_fit = DT.fit(X_train, Y_train)
RF_fit = RF.fit(X_train, Y_train)
#
LR_pred = LR_fit.predict(X_test)
KNN_pred = KNN_fit.predict(X_test)
NB_pred = NB_fit.predict(X_test)
LSVM_pred = LSVM_fit.predict(X_test)
NLSVM_pred = NLSVM_fit.predict(X_test)
DT_pred = DT_fit.predict(X_test)
RF_pred = RF_fit.predict(X_test)
#
print("Logistic Regression is %f percent accurate" % (accuracy_score(LR_pred, Y_test)*100))
print(confusion_matrix(Y_test, LR_pred))  
print ('Report : ') 
print (classification_report(Y_test, LR_pred))
#print ('Accuracy Score :',accuracy_score(Y_test, LR_pred))
#
print("KNN is %f percent accurate" % (accuracy_score(KNN_pred, Y_test)*100))
print(confusion_matrix(Y_test, KNN_pred))  
print ('Report : ') 
print (classification_report(Y_test, KNN_pred))
#
print("Naive Bayes is %f percent accurate" % (accuracy_score(NB_pred, Y_test)*100))
print(confusion_matrix(Y_test, NB_pred))  
print ('Report : ') 
print (classification_report(Y_test, NB_pred))
#
print("Linear SVMs is %f percent accurate" % (accuracy_score(LSVM_pred, Y_test)*100))
print(confusion_matrix(Y_test, LSVM_pred))  
print ('Report : ') 
print (classification_report(Y_test, LSVM_pred))
#
print("Non Linear SVMs is %f percent accurate" % (accuracy_score(NLSVM_pred, Y_test)*100))
print(confusion_matrix(Y_test, NLSVM_pred))  
print ('Report : ') 
print (classification_report(Y_test, NLSVM_pred))
#
print("Decision Trees is %f percent accurate" % (accuracy_score(DT_pred, Y_test)*100))
print(confusion_matrix(Y_test, DT_pred))  
print ('Report : ') 
print (classification_report(Y_test, DT_pred))
#
print("Random Forests is %f percent accurate" % (accuracy_score(RF_pred, Y_test)*100))
print(confusion_matrix(Y_test, RF_pred))  
print ('Report : ') 
print (classification_report(Y_test, RF_pred))

Logistic Regression is 89.964664 percent accurate
[[ 249  214]
 [  70 2297]]
Report : 
              precision    recall  f1-score   support

         0.0       0.78      0.54      0.64       463
         1.0       0.91      0.97      0.94      2367

    accuracy                           0.90      2830
   macro avg       0.85      0.75      0.79      2830
weighted avg       0.89      0.90      0.89      2830

KNN is 88.763251 percent accurate
[[ 227  236]
 [  82 2285]]
Report : 
              precision    recall  f1-score   support

         0.0       0.73      0.49      0.59       463
         1.0       0.91      0.97      0.93      2367

    accuracy                           0.89      2830
   macro avg       0.82      0.73      0.76      2830
weighted avg       0.88      0.89      0.88      2830

Naive Bayes is 88.339223 percent accurate
[[ 287  176]
 [ 154 2213]]
Report : 
              precision    recall  f1-score   support

         0.0       0.65      0.62      0.63       463


In [5]:
#Tuning Parametrs
random_forest = RandomForestClassifier()

params = {'n_estimators': [*range(100, 1100, 100)], 'max_features': [*range(1, 20)]}

rscv = RandomizedSearchCV(estimator=random_forest, param_distributions=params, random_state=0)
rscv.fit(X_train, Y_train)
values = rscv.best_params_
random_forest_best = RandomForestClassifier(n_estimators = values['n_estimators'], max_features = values['max_features'])
random_forest_best.fit(X_train, Y_train)
Y_pred = random_forest_best.predict(X_test)
print("Random Forests before tuning : {0} percent accurate".format(accuracy_score(RF_pred, Y_test)*100))
print("Random Forests after tuning : {0} percent accurate".format(accuracy_score(Y_test, Y_pred)*100))

Random Forests before tuning : 96.25441696113074 percent accurate
Random Forests after tuning : 96.89045936395759 percent accurate


In [6]:
#cross-validation
kfold = KFold(9, shuffle=True, random_state=1)

classifier = RandomForestClassifier()
scores = []

for i in range(9):
    result = next(kfold.split(df), None)
    
    X_train = df.iloc[result[0], 1:19]
    X_test = df.iloc[result[1], 1:19]
    
    y_train = df.iloc[result[0], 0]
    y_test = df.iloc[result[1], 0]
    
    classifier = classifier.fit(X_train,y_train)
    predicted = classifier.predict(X_test)
    scores.append(accuracy_score(y_test, predicted))
    
    

print('Average K-Fold Score :' , np.mean(scores))

Average K-Fold Score : 0.967557251908397


In [7]:
df.to_csv('BankChurnMLfunc.csv')