In [1]:
import pandas
import numpy as np
import seaborn as sns

from matplotlib import pyplot as plt
from matplotlib.colors import ListedColormap

from sklearn.model_selection import train_test_split 
from sklearn.model_selection import KFold
from sklearn.ensemble import RandomForestClassifier  
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
from sklearn import tree
from sklearn import neighbors

Churners = pandas.read_csv("BankChurnersUpdated.csv")
Churners

Attrition_Flag  Customer_Age  Gender  Dependent_count  Education_Level  \
0                  0            44       1                2                2   
1                  0            42       1                5                5   
2                  0            57       0                2                2   
3                  0            45       0                2                2   
4                  0            47       1                1                1   
...              ...           ...     ...              ...              ...   
9197               1            55       0                3                5   
9198               1            41       1                2                4   
9199               1            44       0                1                3   
9200               1            30       1                2                2   
9201               1            43       0                2                2   

      Marital_Status  Income_Category  Card_Category  Months_on_book  \
0                  1            50000              1              36   
1                  2           130000              1              31   
2                  1            20000              1              48   
3                  1            20000              1              37   
4                  0            70000              1              42   
...              ...              ...            ...             ...   
9197               2            50000              1              47   
9198               0            50000              1              25   
9199               1            20000              1              36   
9200               2            50000              1              36   
9201               1            20000              2              25   

      Total_Relationship_Count  ...  Credit_Limit  Total_Revolving_Bal  \
0                            3  ...        4010.0                 1247   
1                            5  ...        6748.0                 1467   
2                            5  ...        2436.0                  680   
3                            6  ...       14470.0                 1157   
4                            5  ...       20979.0                 1800   
...                        ...  ...           ...                  ...   
9197                         4  ...       14657.0                 2517   
9198                         4  ...        4277.0                 2186   
9199                         5  ...        5409.0                    0   
9200                         4  ...        5281.0                    0   
9201                         6  ...       10388.0                 1961   

      Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
0              2763.0                 1.376             1088              24   
1              5281.0                 0.831             1201              42   
2              1756.0                 1.190             1570              29   
3             13313.0                 0.966             1207              21   
4             19179.0                 0.906             1178              27   
...               ...                   ...              ...             ...   
9197          12140.0                 0.166             6009              53   
9198           2091.0                 0.804             8764              69   
9199           5409.0                 0.819            10291              60   
9200           5281.0                 0.535             8395              62   
9201           8427.0                 0.703            10294              61   

      Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  \
0                   0.846                  0.311   
1                   0.680                  0.217   
2                   0.611                  0.279   
3                   0.909                  0.080   
4                   0.929                  0.086   
...               

In [2]:
X = Churners.iloc[:, 6:19].values 
y = Churners.iloc[:, 0].values 
X_train, X_test, y_train, y_test = train_test_split( 
              X, y, test_size = 0.3)

print(X)
print(y)

[[5.0000e+04 1.0000e+00 3.6000e+01 ... 1.0880e+03 2.4000e+01 8.4600e-01]
 [1.3000e+05 1.0000e+00 3.1000e+01 ... 1.2010e+03 4.2000e+01 6.8000e-01]
 [2.0000e+04 1.0000e+00 4.8000e+01 ... 1.5700e+03 2.9000e+01 6.1100e-01]
 ...
 [2.0000e+04 1.0000e+00 3.6000e+01 ... 1.0291e+04 6.0000e+01 8.1800e-01]
 [5.0000e+04 1.0000e+00 3.6000e+01 ... 8.3950e+03 6.2000e+01 7.2200e-01]
 [2.0000e+04 2.0000e+00 2.5000e+01 ... 1.0294e+04 6.1000e+01 6.4900e-01]]
[0 0 0 ... 1 1 1]


In [3]:
classifier1 = tree.DecisionTreeClassifier(max_depth=5) 
classifier1 = classifier1.fit(X_train,y_train) 
predicted1 = classifier1.predict(X_test) 

print ('Confusion Matrix :') 
print(confusion_matrix(y_test, predicted1)) 
print ('Accuracy Score :',accuracy_score(y_test, predicted1)) 
print ('Report : ') 
print (classification_report(y_test, predicted1)) 

Confusion Matrix :
[[2235   68]
 [ 133  325]]
Accuracy Score : 0.9272002897500905
Report : 
              precision    recall  f1-score   support

           0       0.94      0.97      0.96      2303
           1       0.83      0.71      0.76       458

    accuracy                           0.93      2761
   macro avg       0.89      0.84      0.86      2761
weighted avg       0.92      0.93      0.92      2761



In [4]:
classifier2 =  RandomForestClassifier()
classifier2 = classifier2.fit(X_train, y_train)
predicted2 = classifier2.predict(X_test)

print ('Confusion Matrix :') 
print(confusion_matrix(y_test, predicted2)) 
print ('Accuracy Score :',accuracy_score(y_test, predicted2)) 
print ('Report : ') 
print (classification_report(y_test, predicted2)) 

Confusion Matrix :
[[2271   32]
 [  84  374]]
Accuracy Score : 0.9579862368706991
Report : 
              precision    recall  f1-score   support

           0       0.96      0.99      0.98      2303
           1       0.92      0.82      0.87       458

    accuracy                           0.96      2761
   macro avg       0.94      0.90      0.92      2761
weighted avg       0.96      0.96      0.96      2761



In [5]:
n_neighbors = 15


classifier3 = neighbors.KNeighborsClassifier(n_neighbors)
classifier3.fit(X, y)
predicted3 = classifier3.predict(X_test)

print ('Confusion Matrix :') 
print(confusion_matrix(y_test, predicted3)) 
print ('Accuracy Score :',accuracy_score(y_test, predicted3)) 
print ('Report : ') 
print (classification_report(y_test, predicted3)) 


Confusion Matrix :
[[2249   54]
 [ 235  223]]
Accuracy Score : 0.8953277797899312
Report : 
              precision    recall  f1-score   support

           0       0.91      0.98      0.94      2303
           1       0.81      0.49      0.61       458

    accuracy                           0.90      2761
   macro avg       0.86      0.73      0.77      2761
weighted avg       0.89      0.90      0.88      2761



In [6]:
kfold = KFold(9, shuffle=True, random_state=1)

classifier = RandomForestClassifier()
scores = []

for i in range(9):
    result = next(kfold.split(Churners), None)
    
    X_train = Churners.iloc[result[0], 6:19]
    X_test = Churners.iloc[result[1], 6:19]
    
    y_train = Churners.iloc[result[0], 0]
    y_test = Churners.iloc[result[1], 0]
    
    classifier = classifier.fit(X_train,y_train)
    predicted = classifier.predict(X_test)
    scores.append(accuracy_score(y_test, predicted))
    
    print ('Confusion Matrix :') 
    print(confusion_matrix(y_test, predicted)) 
    print ('Accuracy Score :',accuracy_score(y_test, predicted)) 
    print ('Report : ') 
    print (classification_report(y_test, predicted)) 
    

print('Average K-Fold Score :' , np.mean(scores))

Confusion Matrix :


ValueError: Found input variables with inconsistent numbers of samples: [1023, 2761]