In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as mpl
import math 
import seaborn as sea
import statistics
from scipy import stats
from numpy import percentile
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report 
from sklearn.metrics import accuracy_score

In [2]:

#dataset = pd.get_dummies(dataset)


df = pd.read_csv("BankChurnML.csv")
del df["Unnamed: 0"]
del df["CLIENTNUM"]
#del df["Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2"]
#del df["Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1"]


In [3]:
#train and test sets
X = df.iloc[:, 6:19].values 
Y = np.array(df['Attrition_Flag']) 
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [4]:
# Methods of Model Evaluation
LR = LogisticRegression()
KNN = KNeighborsClassifier()
NB = GaussianNB()
LSVM = LinearSVC()
NLSVM = SVC(kernel='rbf')
DT = DecisionTreeClassifier()
RF = RandomForestClassifier()
#
LR_fit = LR.fit(X_train, Y_train)
KNN_fit = KNN.fit(X_train, Y_train)
NB_fit = NB.fit(X_train, Y_train)
LSVM_fit = LSVM.fit(X_train, Y_train)
NLSVM_fit = NLSVM.fit(X_train, Y_train)
DT_fit = DT.fit(X_train, Y_train)
RF_fit = RF.fit(X_train, Y_train)
#
LR_pred = LR_fit.predict(X_test)
KNN_pred = KNN_fit.predict(X_test)
NB_pred = NB_fit.predict(X_test)
LSVM_pred = LSVM_fit.predict(X_test)
NLSVM_pred = NLSVM_fit.predict(X_test)
DT_pred = DT_fit.predict(X_test)
RF_pred = RF_fit.predict(X_test)
#
print("Logistic Regression is %f percent accurate" % (accuracy_score(LR_pred, Y_test)*100))
print(confusion_matrix(Y_test, LR_pred))  
print ('Report : ') 
print (classification_report(Y_test, LR_pred))
#print ('Accuracy Score :',accuracy_score(Y_test, LR_pred))
#
print("KNN is %f percent accurate" % (accuracy_score(KNN_pred, Y_test)*100))
print(confusion_matrix(Y_test, KNN_pred))  
print ('Report : ') 
print (classification_report(Y_test, KNN_pred))
#
print("Naive Bayes is %f percent accurate" % (accuracy_score(NB_pred, Y_test)*100))
print(confusion_matrix(Y_test, NB_pred))  
print ('Report : ') 
print (classification_report(Y_test, NB_pred))
#
print("Linear SVMs is %f percent accurate" % (accuracy_score(LSVM_pred, Y_test)*100))
print(confusion_matrix(Y_test, LSVM_pred))  
print ('Report : ') 
print (classification_report(Y_test, LSVM_pred))
#
print("Non Linear SVMs is %f percent accurate" % (accuracy_score(NLSVM_pred, Y_test)*100))
print(confusion_matrix(Y_test, NLSVM_pred))  
print ('Report : ') 
print (classification_report(Y_test, NLSVM_pred))
#
print("Decision Trees is %f percent accurate" % (accuracy_score(DT_pred, Y_test)*100))
print(confusion_matrix(Y_test, DT_pred))  
print ('Report : ') 
print (classification_report(Y_test, DT_pred))
#
print("Random Forests is %f percent accurate" % (accuracy_score(RF_pred, Y_test)*100))
print(confusion_matrix(Y_test, RF_pred))  
print ('Report : ') 
print (classification_report(Y_test, RF_pred))

Logistic Regression is 90.673026 percent accurate
[[ 184  136]
 [  40 1527]]
Report : 
              precision    recall  f1-score   support

         0.0       0.82      0.57      0.68       320
         1.0       0.92      0.97      0.95      1567

    accuracy                           0.91      1887
   macro avg       0.87      0.77      0.81      1887
weighted avg       0.90      0.91      0.90      1887

KNN is 92.209857 percent accurate
[[ 214  106]
 [  41 1526]]
Report : 
              precision    recall  f1-score   support

         0.0       0.84      0.67      0.74       320
         1.0       0.94      0.97      0.95      1567

    accuracy                           0.92      1887
   macro avg       0.89      0.82      0.85      1887
weighted avg       0.92      0.92      0.92      1887

Naive Bayes is 89.984102 percent accurate
[[ 213  107]
 [  82 1485]]
Report : 
              precision    recall  f1-score   support

         0.0       0.72      0.67      0.69       320


In [5]:
#cross-validation
kfold = KFold(9, shuffle=True, random_state=1)

classifier = RandomForestClassifier()
scores = []

for i in range(9):
    result = next(kfold.split(df), None)
    
    X_train = df.iloc[result[0], 1:19]
    X_test = df.iloc[result[1], 1:19]
    
    y_train = df.iloc[result[0], 0]
    y_test = df.iloc[result[1], 0]
    
    classifier = classifier.fit(X_train,y_train)
    predicted = classifier.predict(X_test)
    scores.append(accuracy_score(y_test, predicted))
    
    

print('Average K-Fold Score :' , np.mean(scores))

Average K-Fold Score : 0.967769296013571
